export const teamInfo = {
    Juventus: { color: '#000000', logo: 'juventus' },
    Milan: { color: '#D91C36', logo: 'milan' },
    Inter: { color: '#00529F', logo: 'inter' },
    Napoli: { color: '#0099FF', logo: 'napoli' },
    Roma: { color: '#F4B731', logo: 'roma' },
    Lazio: { color: '#005B8C', logo: 'lazio' },
    Fiorentina: { color: '#5D2A6B', logo: 'fiorentina' },
    Atalanta: { color: '#1E2A47', logo: 'atalanta' },
    Bologna: { color: '#E70010', logo: 'bologna' },
    Torino: { color: '#9E1B32', logo: 'torino' },
    Cagliari: { color: '#003B5C', logo: 'cagliari' },
    Lecce: { color: '#F7C600', logo: 'lecce' },
    Monza: { color: '#E60012', logo: 'monza' },
    Empoli: { color: '#0099D9', logo: 'empoli' },
    Salernitana: { color: '#9E1B32', logo: 'salernitana' },
    Sassuolo: { color: '#1D1D1B', logo: 'sassuolo' },
    Udinese: { color: '#000000', logo: 'udinese' },
    Spezia: { color: '#000000', logo: 'spezia' },
    Genoa: { color: '#D91C36', logo: 'genoa' },
};