export const teamInfo = {
  Juventus: { color: { primaryColor: '#fffdfd', secondaryColor: '#000000' }, logo: 'Juventus' },
  Milan: { color: { primaryColor: '#D91C36', secondaryColor: '#000000' }, logo: 'AC Milan' },
  Inter: { color: { primaryColor: '#000000', secondaryColor: '#00529F' }, logo: 'Inter' },
  Napoli: { color: { primaryColor: '#0099FF', secondaryColor: '#FFFDFD' }, logo: 'napoli' },
  Roma: { color: { primaryColor: '#F7C600', secondaryColor: '#D91C36' }, logo: 'roma' },
  Lazio: { color: { primaryColor: '#87CEEB', secondaryColor: '#FFFFFF' }, logo: 'lazio' },
  Atalanta: { color: { primaryColor: '#004B9F', secondaryColor: '#FFFFFF' }, logo: 'atalanta' },
  Fiorentina: { color: { primaryColor: '#4B2A7B', secondaryColor: '#FFFFFF' }, logo: 'fiorentina' },
  Torino: { color: { primaryColor: '#800000', secondaryColor: '#FFFFFF' }, logo: 'torino' },
  Sassuolo: { color: { primaryColor: '#009900', secondaryColor: '#000000' }, logo: 'sassuolo' },
  Sampdoria: { color: { primaryColor: '#0059B2', secondaryColor: '#FFFFFF' }, logo: 'sampdoria' },
  Bologna: { color: { primaryColor: '#D52B1E', secondaryColor: '#0B1F51' }, logo: 'bologna' },
  Udinese: { color: { primaryColor: '#000000', secondaryColor: '#FFFFFF' }, logo: 'udinese' },
  Empoli: { color: { primaryColor: '#003399', secondaryColor: '#FFFFFF' }, logo: 'empoli' },
  Lecce: { color: { primaryColor: '#D20000', secondaryColor: '#FFDF00' }, logo: 'lecce' },
  Monza: { color: { primaryColor: '#E03A3E', secondaryColor: '#FFFFFF' }, logo: 'monza' },
  Spezia: { color: { primaryColor: '#000000', secondaryColor: '#FFFFFF' }, logo: 'spezia' },
  Cremonese: { color: { primaryColor: '#E2001A', secondaryColor: '#F5DEB3' }, logo: 'cremonese' },
  Salernitana: {
    color: { primaryColor: '#860038', secondaryColor: '#FFFFFF' },
    logo: 'salernitana',
  },
  Verona: { color: { primaryColor: '#0B3C5D', secondaryColor: '#F2AA4C' }, logo: 'verona' },
};
export const teamLogo = [
  { label: 'Juventus', logo: '/app1/assets/teams/juventus.png' },
  { label: 'Milan', logo: '/app1/assets/teams/milan.png' },
  { label: 'Inter', logo: '/app1/assets/teams/inter.png' },
  { label: 'Napoli', logo: '/app1/assets/teams/napoli.png' },
  { label: 'Roma', logo: '/app1/assets/teams/roma.png' },
  { label: 'Lazio', logo: '/app1/assets/teams/lazio.png' },
  { label: 'Napoli', logo: '/app1/assets/teams/napoli.png' },
  { label: 'Fiorentina', logo: '/app1/assets/teams/fiorentina.png' },
];

export const teamPosition = [
  { code: 'POR', label: 'Portiere' },
  { code: 'DC', label: 'Difensore Centrale' },
  { code: 'TD', label: 'Terzino Destro' },
  { code: 'TS', label: 'Terzino Sinistro' },
  { code: 'CC', label: 'Centrocampista Centrale' },
  { code: 'CDC', label: 'Mediano (Centrocampista Difensivo)' },
  { code: 'COC', label: 'Trequartista (Centrocampista Offensivo)' },
  { code: 'AD', label: 'Ala Destra' },
  { code: 'AS', label: 'Ala Sinistra' },
  { code: 'ATT', label: 'Attaccante Centrale' },
  { code: 'SP', label: 'Seconda Punta' },
];
export const starterCard = [
  {
    role: 'player',
    attributes: {
      VEL: 60,
      TIR: 55,
      PAS: 50,
      DRI: 55,
      DIF: 45,
      FIS: 58,
      RES: 60,
      TEC: 52,
      POS: 53,
      VIZ: 50,
      RIF: 48,
      PAR: 20,
    },
  },
  {
    role: 'portiere',
    attributes: {
      VEL: 40,
      TIR: 20,
      PAS: 35,
      DRI: 25,
      DIF: 25,
      FIS: 55,
      RES: 60,
      TEC: 30,
      POS: 58,
      VIZ: 50,
      RIF: 62,
      PAR: 65,
    },
  },
];
